[CMOB-1503] Design
mariammnamgaladze/QuizzApp pull request #1
Opened 2023-05-18 14:05 UTC by mariammnamgaladze

https://spaceneobank.atlassian.net/browse/CMOB-1503

2023-05-25 10:34 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/space/quizzapp/presentation/dialog/Dialog.kt
> +) {
უკეთესი იქნება dialogFragment კლასით გააკეთო დიალოგი, რომელსაც ტაიპად ექნება თუ რომელი სთეითი აჩვენოს 1 ბთნ თუ ორი და იმ კლასშივე დაჰენდლავ ყველაფერს

2023-05-25 10:35 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/space/quizzapp/presentation/detail/DetailsFragment.kt
> +        )
ბეისში რომ გააკეთო რაიმე ფუნქცია რომელიც ნავიგაციას დაგიჰენდლავს და არ მოგიწევს ყველგან  findNavController().navigate ის წერა

2023-05-25 10:36 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/activity_main.xml
> +        tools:layout_editor_absoluteY="237dp"
ამოსაშლელია ეს

2023-05-25 10:37 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/answers_layout_item.xml
> +    android:layout_marginEnd="@dimen/dimen_30dp"
marginHorizontal

2023-05-25 10:38 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/dialog_layout.xml
> +
extra line )

2023-05-25 10:38 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/fragment_home.xml
> +                android:layout_marginStart="16dp"
dimen

2023-05-25 10:39 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/fragment_home.xml
> +        tools:layout_editor_absoluteY="170dp"
წასაშლელია ესეც

2023-05-25 10:40 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/fragment_questions.xml
> +        android:layout_height="@dimen/dimen_351dp"
ძალიან უცნაური ჰეითია ), ამას ჯობია რამე დინამიური იყოს, სქრინის პერსენთებით ან 0დპ

2023-05-25 10:41 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/subject_layout_item.xml
> +    android:backgroundTint="@color/neutral_03_light_grey"
ესეთ სტატიკურ სიმაღლესაც მოერიდე, რამე ვრაპ კონტენტ ჯობია ან დინამიური ზომა

2023-05-25 18:18 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/dialog/Dialog.kt
> +) {
done ✔️

2023-05-25 18:18 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/detail/DetailsFragment.kt
> +        )
done ✔️

2023-05-25 18:18 UTC, mariammnamgaladze commented on app/src/main/res/layout/activity_main.xml
> +        tools:layout_editor_absoluteY="237dp"
done ✔️

2023-05-25 18:18 UTC, mariammnamgaladze commented on app/src/main/res/layout/answers_layout_item.xml
> +    android:layout_marginEnd="@dimen/dimen_30dp"
done ✔️

2023-05-25 18:18 UTC, mariammnamgaladze commented on app/src/main/res/layout/dialog_layout.xml
> +
done ✔️

2023-05-25 18:18 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_home.xml
> +                android:layout_marginStart="16dp"
done ✔️

2023-05-25 18:19 UTC, mariammnamgaladze commented on app/src/main/res/layout/fragment_questions.xml
> +        android:layout_height="@dimen/dimen_351dp"
done ✔️

2023-05-29 06:47 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/space/quizzapp/presentation/dialog/MyDialogFragment.kt
> +        }
კიდევ ორი სთეითი რომ დაგემატოს დიალოგზე კიდევ ასეთი ორი მეთოდის დამატება არ იქნება მიზანშეწონილი, სხვა რმაე ვიგულისხმე წინა კომენტარში. რაღაც showDialog რმ შექმენა ფაბლიქ მეთოდი და ტაიპი რომ ჩააწოდო რაც დაგიჰენდლავს რა სახის დიალოგი გაჩვენოს სწორი იქნება

2023-05-29 10:40 UTC, AnaRusadze requested changes

2023-05-29 10:40 UTC, AnaRusadze commented on .idea/gradle.xml
დაამატე გიტიგნორში იდეას ფაილები

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/java/com/space/quizzapp/presentation/custom_view/QuizBackgroundCustomView.kt
> +     */
სხვადასხვა დივაისზე ვიზუალური ბაგი თუ გაქვს, ამ პრში დაფიქსე

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/java/com/space/quizzapp/presentation/custom_view/StartBackgroundCustomView.kt
> +        val centerY2 = height * 2 / 3 - verticalOffset
სხვადასხვა დივაისზე ვიზუალური ბაგი თუ გაქვს, ამ პრში დაფიქსე

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/java/com/space/quizzapp/presentation/dialog/MyDialogFragment.kt
> +class MyDialogFragment : DialogFragment() {
MyDialog ცუდი სახელია, შეეცადე My არ გამოიყენო ხოლმე

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/drawable/bkg_blue.png
ეს უნდა დაიხატოს კანვასით, დრავაბლი არ გჭირდება

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_man.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
უნდა იყოს პიენჯი, რადგან ვექტორული არაა

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/drawable/rectange.png
უნდა დაიხატოს კანვასით, ეს წაშალე

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/layout/activity_main.xml
>      android:layout_height="match_parent"
activity_mainს გადაარქვი სახელი

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/layout/answers_layout_item.xml
> +    android:layout_width="@dimen/dimen_343dp"
სტატიკური ზომა არ დაუწერო ამ შემთხვევაში, მარჯინ ჰორიზონტალიც საკმარისია იმისთვის რომ width დინამიურად შეიცვალოს დივაისის მიხედვით

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_details.xml
> +        android:layout_width="@dimen/dimen_195dp"
იგივე აქაც. დიდ რიცხვებს არ ვიყენებთ სიგრძის დასაწერად. მხოლოდ ვუთითებთ გარშემო მარჯინებს

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_questions.xml
> +        android:layout_width="@dimen/dimen_343dp"
იგივე აქაც

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/navigation/nav_graph.xml
> +        android:id="@+id/startFragment"
სტარტს აუთენტიფიკაცია ჯობია

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/values/Styles.xml
> +        <item name="android:textColor">#537FE7</item>
ფერი რესურსებიდან წამოიღე

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="collected_points">შენ დააგროვე 14 ქულა</string>
14 არ უნდა ეწეროს, გამოიყენე სტრინგის ფორმატირების მეთოდი

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
ეს წაშალე

2023-05-29 10:40 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="greeting_text">გამარჯობა,ირაკლი!</string>
ირაკლი არ უნდა ეწეროს, გამოიყენე სტრინგის ფორმატირების მეთოდი

2023-06-01 09:56 UTC, Gio481 approved these changes

2023-06-08 14:00 UTC, merged