[CMOB-1527] Feature/di database implementation
mariammnamgaladze/QuizzApp pull request #2
Opened 2023-05-31 13:11 UTC by mariammnamgaladze

2023-06-01 09:58 UTC, Gio481 commented
ჯირას ლინკი უნდა აღწერაში

2023-06-01 10:19 UTC, Gio481 requested changes

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/data/local/dao/UserDao.kt
> +     fun observeUserByUsername(username: String): Flow<UserEntity>
ცუდი სახელია და ქვერე და დასაფორმატირებელია კოდი

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/data/mapper/mapper.kt
> +
ცარელი ხაზი

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/data/mapper/mapper.kt
> +
ცარელი ხაზი

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/data/mapper/mapper.kt
> +
ცარიელი ხაზი :დ

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/di/DatabaseModule.kt
> +}
ფორმატი არ აწყენდა :დ

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/domain/model/DomainUserModel.kt
> +data class DomainUserModel(
ხაზი გამოტოვე

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/domain/usecase/user/observe_user_info/ObserveUserByUsernameUseCaseImpl.kt
> +class ObserveUserByUsernameUseCaseImpl(private val userRepository: UserRepository) : ObserveUserByUsernameUseCase  {
ცუდი სახელია და რახდება ყველა კლასში ფორმატი უნდა კოდს, რატო არ აქცევ მაგას ყურადღებას

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/detail/viewmodel/DetailsFragmentViewModel.kt
> +class DetailsFragmentViewModel:ViewModel() {
ფრაგმენტი აღარ უნდა

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/dialog/fragment/QuizzDialogFragment.kt
> +            val fragment = QuizzDialogFragment()
QuizzDialogFragment().apply

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/home/fragment/HomeFragment.kt
> +            }
ექსთენშენი გააკეთე

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/home/fragment/HomeFragment.kt
> +                binding.greetingTextView.text = greetingText
ცვლადი აღარაა საჭირო პირდაპირ მიანიჭე გეთ სტრინგი

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/home/fragment/HomeFragment.kt
> +            QuizzDialogFragment.twoButtonState(
twoButtonState ცუდი სახელია

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/home/fragment/HomeFragment.kt
> +                negativeButtonAction = {}
ამას თუ არ იყენებ აღარ დაწერო აქ

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/home/fragment/HomeFragment.kt
> +            ).show(parentFragmentManager, "TwoButtonDialog")
"TwoButtonDialog" ამას რატო აწოდებ, რაში გადგება ?

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/home/viewmodel/HomeFragmentViewModel.kt
> +    private val _activeUsernames = MutableSharedFlow<String>()
ხაზი დაამატე

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/start/fragment/AuthenticationFragment.kt
> +            viewModel.usernameAvailability.collect { result ->
ესქთენშენი გინდა

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/start/fragment/AuthenticationFragment.kt
> +                        Toast.makeText(context, "Invalid username format", Toast.LENGTH_SHORT)
ტოასტის ექსთენშენი გააკეთე, და ეს სტრინგებში გაიტე ეს ტექსტიც ქართულად

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/start/viewmodel/AuthenticationFragmentViewModel.kt
> +    val usernameAvailability: StateFlow<Result<Boolean>> = _usernameAvailability
კლასი, ფუნქცია ცვლადი, გააკეთე რასაც მოიფიქრებ რო ასე ყოველ ჯერზე ორი არ გეწეროს და მხოლოდ ერთი ცვლადი გამოიყენო

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/start/viewmodel/AuthenticationFragmentViewModel.kt
> +            }
არაა სუთა ფუნქცია ოპტიმიზაცია უქენი რამე

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/start/viewmodel/AuthenticationFragmentViewModel.kt
> +        viewModelScope.launch {
ამას არ უნდა დისპეჩერი ?

2023-06-01 10:19 UTC, Gio481 commented on app/src/main/java/com/space/quizzapp/presentation/start/viewmodel/AuthenticationFragmentViewModel.kt
> +                    isActive = true
ისექთივი შეგიძლია დეფოლატად გქონდეს მოდელ კლასში

2023-06-08 13:23 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/common/exception/InvalidUsernameException.kt
> +class InvalidUsernameException(message: String) : Exception(message)
done ✔️

2023-06-08 13:23 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/data/local/dao/UserDao.kt
> +     fun observeUserByUsername(username: String): Flow<UserEntity>
done ✔️

2023-06-08 13:23 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/data/mapper/mapper.kt
> +
done ✔️

2023-06-08 13:23 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/data/mapper/mapper.kt
> +
done ✔️

2023-06-08 13:24 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/di/DatabaseModule.kt
> +}
done ✔️

2023-06-08 13:24 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/domain/model/DomainUserModel.kt
> +data class DomainUserModel(
done ✔️

2023-06-08 13:24 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/domain/usecase/user/observe_user_info/ObserveUserByUsernameUseCaseImpl.kt
> +class ObserveUserByUsernameUseCaseImpl(private val userRepository: UserRepository) : ObserveUserByUsernameUseCase  {
done ✔️

2023-06-08 13:24 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/detail/viewmodel/DetailsFragmentViewModel.kt
> +class DetailsFragmentViewModel:ViewModel() {
done ✔️

2023-06-08 13:25 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/dialog/fragment/QuizzDialogFragment.kt
> +            val fragment = QuizzDialogFragment()
არ გამოდის ამით მერე this-ის დაწერა მიწევს ყველგან ფრაგმენტის ნაცვლად და რა აზრი აქვს

2023-06-08 13:25 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/home/fragment/HomeFragment.kt
> +            }
done ✔️

2023-06-08 13:25 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/home/fragment/HomeFragment.kt
> +                binding.greetingTextView.text = greetingText
done ✔️

2023-06-08 13:25 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/home/viewmodel/HomeFragmentViewModel.kt
> +    private val _activeUsernames = MutableSharedFlow<String>()
done ✔️

2023-06-08 13:25 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/home/viewmodel/HomeFragmentViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
done ✔️

2023-06-08 13:25 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/model/UIUserModel.kt
> +data class UIUserModel(
done ✔️

2023-06-08 13:25 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/domain/model/DomainUserModel.kt
> +data class DomainUserModel(
done ✔️

2023-06-08 13:25 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/domain/usecase/user/active_user/GetCurrentUserInfoUseCaseImpl.kt
> +class GetCurrentUserInfoUseCaseImpl(private val userRepository: UserRepository) : GetCurrentUserInfoUseCase {
done ✔️

2023-06-08 13:26 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/domain/usecase/user/save_user/SaveUserInfoUseCase.kt
> +interface SaveUserInfoUseCase {
done ✔️

2023-06-08 13:26 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/model/UIUserModel.kt
> +
done ✔️

2023-06-08 13:26 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/start/fragment/AuthenticationFragment.kt
> +            viewModel.usernameAvailability.collect { result ->
done ✔️

2023-06-08 13:26 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/start/fragment/AuthenticationFragment.kt
> +                        Toast.makeText(context, "Invalid username format", Toast.LENGTH_SHORT)
done ✔️

2023-06-08 14:07 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/home/fragment/HomeFragment.kt
> +                negativeButtonAction = {}
done ✔️

2023-06-08 14:10 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/home/fragment/HomeFragment.kt
> +            ).show(parentFragmentManager, "TwoButtonDialog")
ჩაწოდებას მთხოვს show-ს დროს და სტრინგად გავატანე უბრალოდ, ისე არ შვება :დ ეხლა ცარიელი სტრინგით შევცვალე :დ

2023-06-08 14:10 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/data/local/entity/UserEntity.kt
> +data class UserEntity(
done ✔️

2023-06-08 14:10 UTC, mariammnamgaladze commented on app/src/main/java/com/space/quizzapp/presentation/start/viewmodel/AuthenticationFragmentViewModel.kt
> +        viewModelScope.launch {
done ✔️

2023-06-22 07:37 UTC, Gio481 approved these changes

2023-06-22 13:20 UTC, gioqemoklidze approved these changes

2023-06-22 15:06 UTC, AnaRusadze approved these changes

2023-06-22 15:06 UTC, merged